### ISSUE TITLE
404 Not found after first click

### ISSUE THREAD

**Issue by enahwe** [timkpaine/jupyterlab_iframe#55]
When I open an Iframe (e.g: https://github.com/timkpaine) I can see the web page, but when I click on a link (e.g: paperboy) I have the following issue:

404 : Not Found
You are requesting a page that does not exist!

Note: I use JupyterLab behind an Apache Reverse Proxy.

Is there a solution ?

Other question : How to backward and forward into the web page ?

Thanks

**Comment by timkpaine** [comment]
I'm assuming you're using jupyterlab without ssl, and so connecting to https://github.com/timkpaine utilizes this library's reverse proxy through python.

This is a workaround only, since certain things will cause it to break. Most likely my links are absolute, which does not work with the reverse proxy.

**Comment by enahwe** [comment]
The Apache Reverse Proxy takes HTTPS requests comming from Internet and forward them towards the JupyterLab instances by using HTTP (because of Intranet).
Thanks for your answer
